[build]
    command = "cd ../.. && yarn && cd packages/manager && yarn build"
    publish = "build"
    functions = "built-lambda"

## Yarn 3 cache does not work out of the box as of Jan 2022. Context:
## https://github.com/netlify/build/issues/1535#issuecomment-1021947989
[build.environment]
    YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"